---
- hosts: proxy:masters:workers
  gather_facts: True

- hosts: proxy
  roles:
    - tinyproxy

# this force reload tinyproxy
- hosts: proxy
  tasks:
    - meta: flush_handlers

# Setting up apt-proxy on master and workers (private ips)
- hosts: proxy:masters:workers
  roles:
    - apt-proxy

# Setting mesh vpn using tinc
- hosts: proxy:masters:workers
  roles:
    - tinc

# Proxy is now listening on tinc ip
- hosts: proxy
  roles:
    - tinyproxy

- hosts: proxy
  tasks:
    - meta: flush_handlers

# Apt proxy now should use tinc ip
- hosts: proxy:masters:workers
  roles:
    - apt-proxy

- import_playbook: docker.yml
