---
# ssh key sharing between first and other masters
- block:
    - stat:
        path: /root/.ssh/id_rsa
      register: first_master_key_query

    - name: Creates an ssh key on first master
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
      when: first_master_key_query.stat.exists == False

    - name: Register pub key on first master
      slurp: src="/root/.ssh/id_rsa.pub"
      register: first_master_key

  when: inventory_hostname == initial_master

- name: Propagate the key to other masters
  authorized_key:
    key: "{{ hostvars[initial_master]['first_master_key'].content | b64decode | trim }}"
    user: root
    state: present
  when: inventory_hostname != initial_master
