- name: Tinyproxy for Ubuntu server
  block:

    - name: Add tinyproxy group
      group:
        name: tinyproxy
        state: present

    - name: Add tinyproxy user
      user:
        name: tinyproxy
        state: present
        group: tinyproxy

    - name: Check for internet access
      shell: |
        curl -IsSL -m5 http://mirrors.ubuntu.com/{% set proxy_hostname = groups['proxy'][0] -%}
        {%- if inventory_hostname != proxy_hostname -%}
          {%- set interface_key = 'ansible_' + proxy_private_interface|default('eth0') -%}
          {%- set http_proxy = hostvars[proxy_hostname][interface_key]['ipv4']['address'] %}
           || http_proxy='http://{{ http_proxy }}:8888' curl -IsSL -m5 http://mirrors.ubuntu.com/
        {%- endif %}
      args:
        warn: False
      register: ping_result
      changed_when: False
      ignore_errors: True

    - name: Continue installation if routable
      block:

        - name: Install tinyproxy on the proxy server
          apt:
            name: tinyproxy
            state: latest

        - name: Ensure tinyproxy is stopped
          systemd:
            name: tinyproxy
            state: stopped

        - name: Templating /etc/tinyproxy.conf
          template:
            src: tinyproxy.conf.j2
            dest: /etc/tinyproxy.conf
          notify: Reload tinyproxy

        - name: Ensure tinyproxy is running
          systemd:
            name: tinyproxy
            state: started

      when: ping_result.rc == 0

  when: ansible_distribution == "Ubuntu"
