---
- name: install docker-py
  apt:
    name: python-docker
    state: latest
  register: result
  retries: 3
  until: result is success

- name: pull docker images
  docker_image: name="{{ item }}"
  with_items:
    - "k8s.gcr.io/kube-apiserver-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-controller-manager-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-proxy-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/kube-scheduler-{{ kube_arch }}:{{ kubernetes_version }}"
    - "k8s.gcr.io/pause-{{ kube_arch }}:3.1"
    - "quay.io/coreos/flannel:{{ cni_version }}-{{ kube_arch }}"

- name: pull etcd if not multimaster
  docker_image: name="k8s.gcr.io/etcd-{{ kube_arch }}:3.1.12"
  when: groups.masters | length == 1
